var canvas;
var clickArea;
var clickAreaImg;
var upgradeImg;
var coins = [];
var totalClicks = 0;
var clickLVL = 1;
var clickAmount = 1;
var upgrade;
var scareImg;
var ben10;
var reeeeGIF;
var reeeeMP3;
var afkTimer = 0;
var gif = false;
var uSize;
